#!/bin/bash

# Set environment variables for Heroku application.

# Salesforce and AWS S3 credentials
heroku config:set \
  OK_WATCH_SALESFORCE_USERNAME=$OK_WATCH_SALESFORCE_USERNAME \
  OK_WATCH_SALESFORCE_PASSWORD=$OK_WATCH_SALESFORCE_PASSWORD \
  OK_WATCH_SALESFORCE_SECURITY_TOKEN=$OK_WATCH_SALESFORCE_SECURITY_TOKEN \
  AWS_ACCESS_KEY_ID=$AWS_OKWATCH_MEMBERSHIP_ACCESS_KEY_ID \
  AWS_SECRET_ACCESS_KEY=$AWS_OKWATCH_MEMBERSHIP_SECRET_ACCESS_KEY \
  AWS_DEFAULT_REGION=$AWS_OKWATCH_MEMBERSHIP_DEFAULT_REGION \
  SLACK_THOMASTHOREN_ACCESS_TOKEN=$SLACK_THOMASTHOREN_ACCESS_TOKEN

travis encrypt \
  OK_WATCH_SALESFORCE_USERNAME=$OK_WATCH_SALESFORCE_USERNAME \
  --add env.global \
  --override  # Delete all and build again
travis encrypt \
  OK_WATCH_SALESFORCE_PASSWORD=$OK_WATCH_SALESFORCE_PASSWORD \
  --add env.global
travis encrypt \
  OK_WATCH_SALESFORCE_SECURITY_TOKEN=$OK_WATCH_SALESFORCE_SECURITY_TOKEN \
  --add env.global
travis encrypt \
  SLACK_THOMASTHOREN_ACCESS_TOKEN=$SLACK_THOMASTHOREN_ACCESS_TOKEN \
  --add env.global
